name: Build jar

on:
  push:
    branches:
      - "!*"
    tags:
      - "v*"

jobs:
  clojure:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Prepare java
        uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          java-version: "15"

      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@3.5
        with:
          cli: latest

      - name: Build bot
        run: clojure -T:build uberjar
        shell: bash

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: target/Doplarr.jar
